;[
	{
		firstName: 'Liam',
		lastName: 'Evelyn',
		email: 'LiamEvelyn@testing.com',
		age: 39,
		salary: 3662,
		department: 'QA Automation Team',
	},
	{
		firstName: 'Mason',
		lastName: 'William',
		email: 'MasonWilliam@testing.com',
		age: 40,
		salary: 3002,
		department: 'Cibersecurity Team',
	},
  {
    firstName: "Angel",
    lastName: "Hackerman",
    email: "AngelHackerman@testing.com", 
    age: "27",
    Salary: "4000",
    Department: "QA Automation Team"
  },
	{
		firstName: 'William',
		lastName: 'Harper',
		email: 'WilliamHarper@testing.com',
		age: 65,
		salary: 6967,
		department: 'Client Support',
	},
	{
		firstName: 'Sophia',
		lastName: 'Charlotte',
		email: 'SophiaCharlotte@testing.com',
		age: 36,
		salary: 3195,
		department: 'Tech Support',
	},
	{
		firstName: 'Olivia',
		lastName: 'Emma',
		email: 'OliviaEmma@testing.com',
		age: 37,
		salary: 3443,
		department: 'Cibersecurity Team',
	},
	{
		firstName: 'Ethan',
		lastName: 'Lucas',
		email: 'EthanLucas@testing.com',
		age: 59,
		salary: 6053,
		department: 'Cibersecurity Team',
	},
	{
		firstName: 'William',
		lastName: 'William',
		email: 'WilliamWilliam@testing.com',
		age: 48,
		salary: 3201,
		department: 'Social Management',
	},
	{
		firstName: 'Mia',
		lastName: 'Emma',
		email: 'MiaEmma@testing.com',
		age: 39,
		salary: 3751,
		department: 'Social Management',
	},
	{
		firstName: 'Emma',
		lastName: 'Elijah',
		email: 'EmmaElijah@testing.com',
		age: 22,
		salary: 4736,
		department: 'Tech Support',
	},
	{
		firstName: 'Mason',
		lastName: 'Harper',
		email: 'MasonHarper@testing.com',
		age: 64,
		salary: 3551,
		department: 'Tech Support',
	},
	{
		firstName: 'James',
		lastName: 'Amelia',
		email: 'JamesAmelia@testing.com',
		age: 46,
		salary: 5663,
		department: 'Social Management',
	},
	{
		firstName: 'James',
		lastName: 'William',
		email: 'JamesWilliam@testing.com',
		age: 48,
		salary: 6715,
		department: 'QA Automation Team',
	},
	{
		firstName: 'Oliver',
		lastName: 'Harper',
		email: 'OliverHarper@testing.com',
		age: 45,
		salary: 6278,
		department: 'Social Management',
	},
	{
		firstName: 'Mason',
		lastName: 'James',
		email: 'MasonJames@testing.com',
		age: 39,
		salary: 5393,
		department: 'QA Automation Team',
	},
	{
		firstName: 'James',
		lastName: 'Evelyn',
		email: 'JamesEvelyn@testing.com',
		age: 46,
		salary: 7688,
		department: 'Data Science Team',
	},
	{
		firstName: 'Oliver',
		lastName: 'Sophia',
		email: 'OliverSophia@testing.com',
		age: 28,
		salary: 3320,
		department: 'Data Science Team',
	},
	{
		firstName: 'Ethan',
		lastName: 'Harper',
		email: 'EthanHarper@testing.com',
		age: 60,
		salary: 7426,
		department: 'Tech Support',
	},
	{
		firstName: 'Sophia',
		lastName: 'Oliver',
		email: 'SophiaOliver@testing.com',
		age: 64,
		salary: 5180,
		department: 'Tech Support',
	},
	{
		firstName: 'Ethan',
		lastName: 'Oliver',
		email: 'EthanOliver@testing.com',
		age: 26,
		salary: 4927,
		department: 'Tech Support',
	},
]
